OMP_NUM_THREADS=8 python fed_train.py \
    --dataset_path /data/drothchild/datasets/cifar10/ \
    --local_batch_size 128 \
    --local_momentum 0.0 \
    --virtual_momentum 0.9 \
    --error_type virtual \
    --mode sketch \
    --num_devices 4 \
    --num_workers 4 \
    --k 50000 \
    --num_rows 3 \
    --num_cols 1000000 \
    --supervised \
    --share_ps_gpu
